### PR TITLE
Update the README

### PR DESCRIPTION
**Pull request by RGaonkar**
for the running the app, need to run the docker-compose command with root priviledges :

sudo docker-compose up
INSTEAD OF
docker-compose up 

At least, for me, it did not work without the root privileges

### CODE REVIEW

**Comment by peterbe** [comment]
@lcamacho Wanna review this one?

**Comment by lcamacho** [comment]
@RGaonkar can you execute in your terminal `which docker-compose` and paste the output here

**Comment by RGaonkar** [comment]
@lcamacho Here's the output 
```
/usr/local/bin/docker-compose

```
This was the error I was getting initially:

```
Couldn't connect to Docker daemon at http+unix://var/run/docker.sock - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

```
I looked up this link. Running it as a super user was one of the suggestions. I don't know if this should be used over setting the DOCKER_HOST environment variable
https://github.com/docker/compose/issues/88

**Comment by lcamacho** [comment]
@RGaonkar what distro are you using? if Mint check this comment https://github.com/docker/compose/issues/88#issuecomment-76683102

**Comment by lcamacho** [comment]
@RGaonkar or maybe set the DOCKER_HOST in your `.bashrc` like suggested here https://github.com/docker/compose/issues/88#issuecomment-66447696

**Comment by lcamacho** [comment]
@RGaonkar so did you finally get docker-compose work without sudo?

**Comment by RGaonkar** [comment]
@lcamacho Yes! It works without the sudo. Thanks a lot for the pointers! But, while I run docker-compose up, I am getting an error as follows : 
```
django.db.utils.OperationalError: could not connect to server: No such file or directory
web_1       | 	Is the server running locally and accepting
web_1       | 	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

```
There is no socket file called .s.PGSQL.5432 in the postgresql directory. Is it due to this missing socket file?

**Comment by lcamacho** [comment]
Check that your database host in `settings/local.py` is `db`

**Comment by RGaonkar** [comment]
@lcamacho Ah yes. Strongly apologize for overlooking this . Its completely functional now. I have also run the tests and the ssh into the container. Everything works fine. Many thanks!

**Comment by peterbe** [comment]
@lcamacho I didn't need sudo. Is this PR good?

**Comment by lcamacho** [comment]
No, nobody has to use sudo to run docker.

**Comment by peterbe** [comment]
So shall we close this PR?

**Comment by lcamacho** [comment]
I think so

**Pull request closed without merging**
