### PR TITLE
fixes bug 1141293 - No test coverage of curated_groups_map

### PR DESCRIPTION
**Pull request by blossomica**
@peterbe - I tried to fix this bug. Let me know if it is okay or it needs any changes. Thank you.

### CODE REVIEW

**Comment by peterbe** [comment]
You continue to impress! Perhaps we need to find you a slightly harder bug.

**Comment by blossomica** [comment]
@peterbe - Thanks :smile today I was thinking of asking some feedback on how you think I am doing so far, and if you have any general feedback for me, as I wanted to make sure I am on the right track. This is really encouraging to read thank you!

**Comment by peterbe** [comment]
I'm writing you an essay about how to work on this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1154490

**Comment by peterbe** [comment]
Feedback? You're doing great. 
You're getting more and more familiar with the process so you need to attempt harder bugs. It's hard to know which ones are slightly harder and which ones are too much harder (so to say). 
Keep checking, when you see a bug you like, "Is this a good bug to work on? If so, what does X and Y mean?"

But still, there's still plenty of `[good first bug]` bugs to work on and every time you do one, you're getting better and better.

**Comment by blossomica** [comment]
@peterbe - All right, thanks again. I will look at the new harder bug and will start working on it.

**Pull request merged**
