### PR TITLE
adding julian.alexander.murillo to contributors

### PR DESCRIPTION
**Pull request by peterbe**
@64lines check it out! :)

### CODE REVIEW

**Comment by peterbe** [comment]
Now you need to find another more challenging bug @64lines 
But if you like, keep taking bugs that are marked as "good first bugs".

**Comment by peterbe** [comment]
Why isn't travis working on this?!

**Comment by peterbe** [comment]
See if re-opening helps.

**Comment by 64lines** [comment]
@peterbe This is so cool!

**Comment by 64lines** [comment]
I'm going to check out another bug to work on, :smiley:

**Pull request merged**
