### PR TITLE
Fixes bug 1147657 - Limit position: absolute to where necessary

### PR DESCRIPTION
**Pull request by bugzPDX**

### CODE REVIEW

**Comment by peterbe** [comment]
Lamest excuse in the world, but I can't (manually) test this because you're behind on `staticpages/models.py` which now breaks with my more up-to-data postgres database. Would you mind rebasing it up to master's latest?

**Comment by bugzPDX** [comment]
@peterbe I should be up to date now.

**Comment by peterbe** [comment]
No star when viewing the event:
screenshot 2015-03-27 14 38 35

**Comment by peterbe** [comment]
I suspect this is failing because of something I fixed in master. Can you rebase this up one more time?

**Comment by peterbe** [comment]
Sorry for the long delay. Now you can rebase up against latest & greatest master.

**Pull request merged**
