### PR TITLE
Fix bug 1141300 - Deprecate EventFindForm

### PR DESCRIPTION
**Pull request by blossomica**
I think I fixed this.
Let me know if it is okay.
Thank you.

### CODE REVIEW

**Comment by peterbe** [comment]
Well done. Let's see what Travis has to say.

**Comment by blossomica** [comment]
Thanks. I am waiting for its results too.

**Comment by peterbe** [comment]
I'm reopening so that Travis starts again. It seems it got stuck.

**Comment by blossomica** [comment]
Has that happen before?

**Comment by peterbe** [comment]
Rarely. But has happened.

**Comment by blossomica** [comment]
Oh, okay. I hope it completes soon.

**Pull request merged**
