### PR TITLE
Bug1141288 fixing removal html to text function

### PR DESCRIPTION
**Pull request by swetarani**
@peterbe Please, have a look.

### CODE REVIEW

**Comment by peterbe** [comment]
Can you please rebase that into 1 single commit? Do you know how to rebase? If not, perhaps ask anybody in #airmozilla-dev for some help.

**Comment by swetarani** [comment]
Done.

**Comment by peterbe** [comment]
So, what you need to do next is rebase and squash it into 1 commit. 
After you have updated your master branch to the latest, switch to the `bug1141288-fixing-Removal-html_to_text-function` branch and type: `git rebase -i master`.

It'll start your editor and list 4 commits with the word "pick" prefixing all of them. Make it so it says:
```
pick 
f
f
f
```
and save the file and the git rebase will squash the last three commit into the first one and keep the commit message of the first one. 

After that you need to force push to your remote fork.

**Comment by swetarani** [comment]
@peterbe I did the same.
Is it wrong what I have done

**Comment by peterbe** [comment]
You pinged me on IRC. Now I'm a bit confused as to what the latest is. Did you try squashing again?
When you're done you're supposed to just have 1 commit.

**Comment by swetarani** [comment]
@peterbe Actually, last night I had followed http://stackoverflow.com/a/2568581 for rebasing. According to this I had done "pick" for old commit and "s" (squash) for second commit in the text editor. After that I did git pull and then git push.
So, I had done squashing yesterday. I haven't made any changes after our latest discussion.

**Comment by blossomica** [comment]
@swetarani - Just a little suggestion. Yesterday I tried to figure out how to rebase a commit because I had no clue on it and I was able to do it, so I thought maybe I can help you somehow. You will know you have done the rebase-squash or fixup correctly when you come to this repository and see only 1 git commit with all the changes you want to keep ( at least that is how I got to know in my case, right now you have 4 so that will become 1 if you do it correctly). 

I am not sure if the rebase you did worked but in case it did you can first run

    git rebase --abort

in the in the branch you rebased.

Peterbe mentioned you should update your master branch to the latest. If you are currently inside your bug114... branch you will have to checkout to your master. 
You can do that with

     git checkout master 

Once you are in your master branch you should add the official airmozilla repo as a remote. To do that you can run:

     git remote add upstream https://github.com/mozilla/airmozilla.git

Once you have done that you can verify that you did that correctly by running:

    git remote -v

You should see upstream in the list of repositories. 

Now you have to fetch the latest changes from the remote repository

      git fetch upstream

Then you can merge the changes to your own master branch

    git merge upstream/master

After that you can switch to your  `bug1141288-fixing-Removal-html_to_text-function` branch and run the commands peterbe told you `git rebase -i master`. Make sure you save the changes after selecting your options. Also peterbe mentioned you should use "f" which means fixup so if the rebase you tried earlier didn't work in your next attempt use "f" instead of "s". I hope this helps you in some way. 

After you have done the rebase, you will get a warning when you try to push it here if you do it with the regular `git push origin ....` command . You should do a force push in that case. 

I hope my instructions are correct, I am also a newbie, so if I have done anything wrong you can let me know :)

**Comment by swetarani** [comment]
@blossomica Thanks a lot. it helped me too :)

**Comment by blossomica** [comment]
Great! :)

**Pull request merged**
