### PR TITLE
Bug-1186669 Re-enable selenium tests

### PR DESCRIPTION
**Pull request by lcamacho**
@peterbe please review

### CODE REVIEW

**Comment by peterbe** [comment]
Same old error :(

**Comment by lcamacho** [comment]
Weird things of selenium, on local if executed only selenium tests is ok but if executed the complete battery of tests then fails, which is what occurs on travis. The fail is that on first case calendar.js detect 'America/Los_Angeles' tz but latter case detect the right timezone which is UTC, no idea of how this can happen.

**Comment by lcamacho** [comment]
@peterbe please trigger a new build

**Comment by peterbe** [comment]
Re-opening does that.

**Comment by lcamacho** [comment]
weird fails, not related to calendar, keep appearing on travis

**Comment by lcamacho** [comment]
green light

**Comment by peterbe** [comment]
What a trip! I'm snowed under at the moment on a different project and can't spend super much attention on this but I'm glad it's getting greener.

**Pull request merged**
