### PR TITLE
Changes to fix the Bug 1201143

### PR DESCRIPTION
**Pull request by 64lines**
This change is for consolidating the STOPWORDS list according to the 1201143 bug tracker.

### CODE REVIEW

**Comment by peterbe** [comment]
Hi @64lines! Welcome to the community. 

As you can see, you have some pyflakes errors. Do you see that?

One way to prevent this from happening is to first run `pyflakes` and `pep8` on the files before you commit. One way to do that is to use `flake8`. (`pip install flake8`). 
You can set up a git pre-commit hook like this:
1) pip install flake8
2) Download https://gist.github.com/peterbe/0fab292e657d003533b9
3) Save it as `.git/hooks/pre-commit` in the repo root directory

**Comment by 64lines** [comment]
Hi @peterbe, 

Thank you for the advice! I'm running the command right now and fixing the possible problems.

**Comment by peterbe** [comment]
If you run `flake8` on that `search/utils.py` page it'll tell you what's wrong.

**Comment by peterbe** [comment]
We can ignore the coveralls errors. I know the change is good.

So, the process we run is that when you get a final "r+" comment from me, the next thing you need to do is do one last rebase and squash and re-write the commit message. 

Here it is: r+

Now please rebase and squash it down to just 1 commit. The commit message should be: `fixes 1201143 - consolidating use of STOPWORDS list`

**Comment by peterbe** [comment]
Next, you're now a welcomed contributor to be added to https://air.mozilla.org/contributors/

What you need to do is create a Mozillians profile and get yourself vouched. Once you've set up your profile you can ping me and I'll vouch you in. 

Then, once you've done that (AND if you have a name and a picture on your Mozillian profile) is that you need to apply to be a member of the curated group https://mozillians.org/en-US/group/air-mozilla-contributors/

Ping me when you've applied and I'll take care of adding you [to the list](https://github.com/mozilla/airmozilla/blob/3b530a70b685ce529960694ea4a3cd97cf75dc40/airmozilla/settings/base.py#L312).

**Comment by 64lines** [comment]
Thank you @peterbe, I will!

**Pull request merged**
