### PR TITLE
Fix bug 1142322 - Update bootstrap to 3.3.2

### PR DESCRIPTION
**Pull request by kenrick95**
Fixing [bug 1142322](https://bugzilla.mozilla.org/show_bug.cgi?id=1142322).

### CODE REVIEW

**Comment by peterbe** [comment]
I think this is missing `glyphicons-halflings*.png` and `fonts/glyphicons-halflings-regular.*`

**Comment by kenrick95** [comment]
I think Bootstrap never have `glyphicons-halfings*.png`. And yeah, I've updated `fonts/glyphicons-halflings-regular.*`. Am I missing anything else?

**Comment by peterbe** [comment]
So I guess we ought to delete https://github.com/mozilla/airmozilla/blob/master/airmozilla/manage/static/manage/img/glyphicons-halflings.png

**Comment by peterbe** [comment]
I'm going to delete the glyphicon PNG icons.

**Comment by peterbe** [comment]
By the way, thank you so much for that change!
Do you want something a little harder to work on?

**Comment by kenrick95** [comment]
You're welcome.
Sure, that would be great :smile:

**Comment by peterbe** [comment]
@kenrick95 How good are you with Django? Would you be interested in writing a new app for static pages? We're currently using `django.contrib.flatpages.FlatPage` to store what we call a "static page". 
So, this would involve writing a new app, and a new model called `StaticPage` and basically take much of the functionality of `django.contrib.flatpages` and bring that across.

Or perhaps you want to work on the [HTML emails and make them a bit prettier](https://bugzilla.mozilla.org/show_bug.cgi?id=1053353). Or HTML emails work but they're not very well aligned as a table and there's no "air mozilla feeling" to them. 

Another thing to work on would be to integrate [Aviary](https://developers.aviary.com/) with the picture gallery so that when you can take a picture from the gallery, edit it in a Aviary pop-up and save back as a new image. 

Or, perhaps you can build our [Air Mozilla Kodi app](https://bugzilla.mozilla.org/show_bug.cgi?id=1139639). Kodi is a media player that works on things like RasperryPi but first of all, it works amazingly on a regular OSX or Linux or Windows.

**Comment by kenrick95** [comment]
I just started learning Django for my other work and I think I will focus my Django learning for that personal work first.

Maybe I'll take the HTML email stuff. May I know where the current HTML email template located at?

Thanks for helping :grin:

**Comment by peterbe** [comment]
A lot of the email templates look like this for example https://github.com/mozilla/airmozilla/blob/master/airmozilla/manage/templates/manage/_email_approval.html
The template filename starts with `_email`. 
But the master template ti work on would be this: https://github.com/mozilla/airmozilla/blob/master/airmozilla/base/templates/email_base.html

**Pull request merged**
